/**
 * @desc Here will be list of mutation for store
 */
/* LOCALIZATION */
export const SET_SPINNER = 'SET_SPINNER'
export const SET_LANGUAGE = 'SET_LANGUAGE'
export const GET_LOCALE = 'GET_LOCALE'
export const GET_COUNTRY_NAME = 'GET_COUNTRY_NAME'
export const BLOCK_USER_COUNTRY = 'BLOCK_USER_COUNTRY'

/* USER */
export const SET_COUNTRIES_LIST = 'SET_COUNTRIES_LIST'
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER'
export const GET_CLOSED_POSITIONS = 'GET_CLOSED_POSITIONS'
export const GET_ASSETS_LIST = 'GET_ASSETS_LIST'
export const DEAUTHENTICATE_USER = 'DEAUTHENTICATE_USER'
export const SET_PROFILE_DETAILS = 'SET_PROFILE_DETAILS'
export const SET_PROFILE_DETAILS_ANONYMOUS = 'SET_PROFILE_DETAILS_ANONYMOUS'
export const GET_TRANSACTIONS_LIST = 'GET_TRANSACTIONS_LIST'
// export const GET_DEPOSITS_LIST = 'GET_DEPOSITS_LIST'
// export const GET_WITHDRAWALS_LIST = 'GET_WITHDRAWALS_LIST'
export const UPDATE_BALANCE_AFTER_WITHDRAWALS = 'UPDATE_BALANCE_AFTER_WITHDRAWALS'
export const GET_DOCUMENTS_LIST = 'GET_DOCUMENTS_LIST'

// export const SET_ARTICLES = 'SET_ARTICLES'
// export const SET_CURRENT_ARTICLE = 'SET_CURRENT_ARTICLE'

export const CLEAR_PROFILE_DATA = 'CLEAR_PROFILE_DATA'
export const SET_SERVER_ERROR = 'SET_SERVER_ERROR'

export const SET_MATCHED = 'SET_MATCHED'
export const SET_CURRENCIES = 'SET_CURRENCIES'
export const SET_CURRENT_SSO = 'SET_CURRENT_SSO'
export const AUTHENTICATE_MANAGER = 'AUTHENTICATE_MANAGER'

